// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timeseries.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	timeseries.proto

It has these top-level messages:
	TSErr
	TSPoint
	Query
	Response
	Point
	Meta
	Tag
	MetaFound
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type TSErr struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *TSErr) Reset()                    { *m = TSErr{} }
func (m *TSErr) String() string            { return proto1.CompactTextString(m) }
func (*TSErr) ProtoMessage()               {}
func (*TSErr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TSErr) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type TSPoint struct {
	Ksid  string  `protobuf:"bytes,1,opt,name=ksid" json:"ksid,omitempty"`
	Tsid  string  `protobuf:"bytes,2,opt,name=tsid" json:"tsid,omitempty"`
	Value float32 `protobuf:"fixed32,3,opt,name=value" json:"value,omitempty"`
	Date  int64   `protobuf:"varint,4,opt,name=date" json:"date,omitempty"`
}

func (m *TSPoint) Reset()                    { *m = TSPoint{} }
func (m *TSPoint) String() string            { return proto1.CompactTextString(m) }
func (*TSPoint) ProtoMessage()               {}
func (*TSPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TSPoint) GetKsid() string {
	if m != nil {
		return m.Ksid
	}
	return ""
}

func (m *TSPoint) GetTsid() string {
	if m != nil {
		return m.Tsid
	}
	return ""
}

func (m *TSPoint) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *TSPoint) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

type Query struct {
	Ksid  string `protobuf:"bytes,1,opt,name=ksid" json:"ksid,omitempty"`
	Tsid  string `protobuf:"bytes,2,opt,name=tsid" json:"tsid,omitempty"`
	Start int64  `protobuf:"varint,3,opt,name=start" json:"start,omitempty"`
	End   int64  `protobuf:"varint,4,opt,name=end" json:"end,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto1.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Query) GetKsid() string {
	if m != nil {
		return m.Ksid
	}
	return ""
}

func (m *Query) GetTsid() string {
	if m != nil {
		return m.Tsid
	}
	return ""
}

func (m *Query) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Query) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type Response struct {
	Pts []*Point `protobuf:"bytes,1,rep,name=pts" json:"pts,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetPts() []*Point {
	if m != nil {
		return m.Pts
	}
	return nil
}

type Point struct {
	Value float32 `protobuf:"fixed32,1,opt,name=Value" json:"Value,omitempty"`
	Date  int64   `protobuf:"varint,2,opt,name=Date" json:"Date,omitempty"`
	Empty bool    `protobuf:"varint,3,opt,name=Empty" json:"Empty,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto1.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Point) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Point) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *Point) GetEmpty() bool {
	if m != nil {
		return m.Empty
	}
	return false
}

type Meta struct {
	Ksid   string `protobuf:"bytes,1,opt,name=ksid" json:"ksid,omitempty"`
	Tsid   string `protobuf:"bytes,2,opt,name=tsid" json:"tsid,omitempty"`
	Metric string `protobuf:"bytes,3,opt,name=metric" json:"metric,omitempty"`
	Tags   []*Tag `protobuf:"bytes,4,rep,name=tags" json:"tags,omitempty"`
}

func (m *Meta) Reset()                    { *m = Meta{} }
func (m *Meta) String() string            { return proto1.CompactTextString(m) }
func (*Meta) ProtoMessage()               {}
func (*Meta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Meta) GetKsid() string {
	if m != nil {
		return m.Ksid
	}
	return ""
}

func (m *Meta) GetTsid() string {
	if m != nil {
		return m.Tsid
	}
	return ""
}

func (m *Meta) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *Meta) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Tag struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Tag) Reset()                    { *m = Tag{} }
func (m *Tag) String() string            { return proto1.CompactTextString(m) }
func (*Tag) ProtoMessage()               {}
func (*Tag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Tag) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Tag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MetaFound struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *MetaFound) Reset()                    { *m = MetaFound{} }
func (m *MetaFound) String() string            { return proto1.CompactTextString(m) }
func (*MetaFound) ProtoMessage()               {}
func (*MetaFound) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MetaFound) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto1.RegisterType((*TSErr)(nil), "proto.TSErr")
	proto1.RegisterType((*TSPoint)(nil), "proto.TSPoint")
	proto1.RegisterType((*Query)(nil), "proto.Query")
	proto1.RegisterType((*Response)(nil), "proto.Response")
	proto1.RegisterType((*Point)(nil), "proto.Point")
	proto1.RegisterType((*Meta)(nil), "proto.Meta")
	proto1.RegisterType((*Tag)(nil), "proto.Tag")
	proto1.RegisterType((*MetaFound)(nil), "proto.MetaFound")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Timeseries service

type TimeseriesClient interface {
	Write(ctx context.Context, in *TSPoint, opts ...grpc.CallOption) (*TSErr, error)
	Read(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Response, error)
	GetMeta(ctx context.Context, in *Meta, opts ...grpc.CallOption) (*MetaFound, error)
}

type timeseriesClient struct {
	cc *grpc.ClientConn
}

func NewTimeseriesClient(cc *grpc.ClientConn) TimeseriesClient {
	return &timeseriesClient{cc}
}

func (c *timeseriesClient) Write(ctx context.Context, in *TSPoint, opts ...grpc.CallOption) (*TSErr, error) {
	out := new(TSErr)
	err := grpc.Invoke(ctx, "/proto.Timeseries/Write", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeseriesClient) Read(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/proto.Timeseries/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeseriesClient) GetMeta(ctx context.Context, in *Meta, opts ...grpc.CallOption) (*MetaFound, error) {
	out := new(MetaFound)
	err := grpc.Invoke(ctx, "/proto.Timeseries/GetMeta", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Timeseries service

type TimeseriesServer interface {
	Write(context.Context, *TSPoint) (*TSErr, error)
	Read(context.Context, *Query) (*Response, error)
	GetMeta(context.Context, *Meta) (*MetaFound, error)
}

func RegisterTimeseriesServer(s *grpc.Server, srv TimeseriesServer) {
	s.RegisterService(&_Timeseries_serviceDesc, srv)
}

func _Timeseries_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TSPoint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeseriesServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Timeseries/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeseriesServer).Write(ctx, req.(*TSPoint))
	}
	return interceptor(ctx, in, info, handler)
}

func _Timeseries_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeseriesServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Timeseries/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeseriesServer).Read(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _Timeseries_GetMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Meta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeseriesServer).GetMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Timeseries/GetMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeseriesServer).GetMeta(ctx, req.(*Meta))
	}
	return interceptor(ctx, in, info, handler)
}

var _Timeseries_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Timeseries",
	HandlerType: (*TimeseriesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _Timeseries_Write_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Timeseries_Read_Handler,
		},
		{
			MethodName: "GetMeta",
			Handler:    _Timeseries_GetMeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "timeseries.proto",
}

func init() { proto1.RegisterFile("timeseries.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcd, 0xae, 0xda, 0x30,
	0x10, 0x85, 0xc9, 0x1f, 0x3f, 0x03, 0xa2, 0xc8, 0x42, 0x55, 0x4a, 0x25, 0x14, 0x79, 0x43, 0x84,
	0x54, 0x16, 0xf4, 0x15, 0x4a, 0x59, 0x55, 0x6a, 0x4d, 0x04, 0x8b, 0xae, 0xdc, 0x66, 0x8a, 0xa2,
	0x94, 0x24, 0xb2, 0x4d, 0xa5, 0xbc, 0x42, 0x9f, 0xfa, 0xca, 0xe3, 0x84, 0x7b, 0x97, 0xf7, 0xae,
	0x38, 0xe7, 0xd8, 0x8c, 0xbf, 0x99, 0x09, 0x2c, 0x4c, 0x71, 0x43, 0x8d, 0xaa, 0x40, 0xbd, 0x6b,
	0x54, 0x6d, 0x6a, 0x16, 0xd1, 0x0f, 0xff, 0x00, 0x51, 0x76, 0x3a, 0x28, 0xc5, 0x16, 0x10, 0xa0,
	0x52, 0xb1, 0x97, 0x78, 0xe9, 0x44, 0x58, 0xc9, 0x7f, 0xc2, 0x28, 0x3b, 0x7d, 0xaf, 0x8b, 0xca,
	0x30, 0x06, 0x61, 0xa9, 0x8b, 0xbc, 0x3b, 0x25, 0x6d, 0x33, 0x63, 0x33, 0xdf, 0x65, 0x56, 0xb3,
	0x25, 0x44, 0xff, 0xe4, 0xdf, 0x3b, 0xc6, 0x41, 0xe2, 0xa5, 0xbe, 0x70, 0xc6, 0xde, 0xcc, 0xa5,
	0xc1, 0x38, 0x4c, 0xbc, 0x34, 0x10, 0xa4, 0xf9, 0x05, 0xa2, 0x1f, 0x77, 0x54, 0xed, 0x5b, 0x4a,
	0x6b, 0x23, 0x95, 0xa1, 0xd2, 0x81, 0x70, 0x86, 0xa8, 0xab, 0xbc, 0xab, 0x6c, 0x25, 0xdf, 0xc2,
	0x58, 0xa0, 0x6e, 0xea, 0x4a, 0x23, 0x5b, 0x43, 0xd0, 0x18, 0x1d, 0x7b, 0x49, 0x90, 0x4e, 0xf7,
	0x33, 0xd7, 0xf8, 0x8e, 0x3a, 0x12, 0xf6, 0x80, 0x1f, 0x21, 0x72, 0xfd, 0x2d, 0x21, 0x3a, 0x13,
	0xb7, 0xe7, 0xb8, 0xcf, 0x3d, 0xf7, 0x17, 0xcb, 0xed, 0x3b, 0x6e, 0xab, 0xed, 0xcd, 0xc3, 0xad,
	0x31, 0x2d, 0x61, 0x8c, 0x85, 0x33, 0xfc, 0x0f, 0x84, 0xdf, 0xd0, 0xc8, 0x57, 0x37, 0xf3, 0x1e,
	0x86, 0x37, 0x34, 0xaa, 0xf8, 0x4d, 0x65, 0x26, 0xa2, 0x73, 0x6c, 0x0d, 0xa1, 0x91, 0x57, 0x1d,
	0x87, 0x44, 0x0c, 0x1d, 0x71, 0x26, 0xaf, 0x82, 0x72, 0xfe, 0x09, 0x82, 0x4c, 0x5e, 0x6d, 0xd7,
	0x25, 0xb6, 0xfd, 0xae, 0x4a, 0x6c, 0x9f, 0x07, 0xef, 0x5e, 0x71, 0x86, 0x7f, 0x84, 0x89, 0xc5,
	0xfa, 0x5a, 0xdf, 0xab, 0x9c, 0xcd, 0xc1, 0xaf, 0x4b, 0xfa, 0xcf, 0x58, 0xf8, 0x75, 0xb9, 0xff,
	0xef, 0x01, 0x64, 0x8f, 0xaf, 0x82, 0x6d, 0x20, 0xba, 0xa8, 0xc2, 0x20, 0x9b, 0xf7, 0xaf, 0xba,
	0xdd, 0xaf, 0x66, 0x0f, 0x7f, 0x50, 0x8a, 0x0f, 0xd8, 0x06, 0x42, 0x81, 0x32, 0x67, 0x7d, 0x4e,
	0x6b, 0x5c, 0xbd, 0xeb, 0x5c, 0x3f, 0x7b, 0x3e, 0x60, 0x5b, 0x18, 0x1d, 0xd1, 0xd0, 0x5c, 0xa6,
	0xdd, 0xa9, 0x35, 0xab, 0xc5, 0x0b, 0x43, 0x68, 0x7c, 0xf0, 0x6b, 0x48, 0xd1, 0xe7, 0xa7, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xf8, 0xe9, 0x83, 0xb7, 0xa8, 0x02, 0x00, 0x00,
}
