#!/usr/bin/env bash
PACKAGE='github.com/uol/mycenae'



usage() {
	echo "${0} [0-9] [true|false]"
}

[ -z "${1}" ] && usage && exit 1
[ -z "${2}" ] && usage && exit 1

if ! make -C "${GOPATH}/src/${PACKAGE}" build ; then
    exit 1
fi

for fname in mycenae ; do
    cp "${GOPATH}/src/${PACKAGE}/${fname}" .
done


CASSANDRA_HOST=$(docker inspect --format "{{ .NetworkSettings.IPAddress }}" consulCassandra1)
ELASTIC_HOST=$(docker inspect --format "{{ .NetworkSettings.IPAddress }}" elastic)
sed \
    --expression "s|CASSANDRA_HOST|${CASSANDRA_HOST}|g" \
    --expression "s|ELASTIC_HOST|${ELASTIC_HOST}|g" \
    "docker.toml" > "docker.local.toml"

docker build --tag "mycenae:develop" .

#
# Mycenae POD
#

name="client-mycenae${1}"
publish="${2:-false}"

docker rm -f "${name}"

arguments=(
    '--hostname' "${name}"
    '--name' "${name}"
    '--dns' "127.0.0.1"
    '--volume' "$(pwd)/ssl:/ssl:ro"
    '--volume' "$(pwd)/ssl.json:/config/ssl.json:ro"
    '--volume' "$(pwd)/consul-mycenae.json:/consul/config/service.json"
)

if [ "${publish}" == "true" ]; then
	arguments=( ${arguments[@]} '--publish' '8787:8080' )  
fi

server=$(docker inspect --format "{{ .NetworkSettings.IPAddress }}" consulServer)

consul_arguments=(
    'agent'
    '--join' "${server}"
    '--retry-join' "${server}"
    '-node-id' "$(/usr/bin/uuidgen)"
)

docker run --detach "${arguments[@]}" consul:0.7.3 "${consul_arguments[@]}"

sleep "10s"


tmpdir=/tmp/${name}
mkdir -p ${tmpdir}
pod_arguments=(
    '--network' "container:${name}"
    '--volume' "${tmpdir}:/tmp/mycenae"
    '--volume' "$(pwd)/ssl:/ssl:ro"
)
docker run "${pod_arguments[@]}" "mycenae:develop"
